mixed-port: 7890                       
redir-port: 7891                       
tproxy-port: 7892                      
geodata-mode: true                     
tcp-concurrent: true                   
allow-lan: true                        
bind-address: '*'                      
mode: rule                             
log-level: info                     
ipv6: false                             
external-controller: ':9999'    


sniffer:                               
  enable: true                         
  sniffing:                            
    - tls
    - http

  skip-domian:                         
    - 'Mijia Cloud'                    
    - '+.apple.com'                    
  # - '*.baidu.com'                    

  force-domain:                        
  # - '+'                              
    - 'google.com'


dns:
  enable: true                         
  listen: 0.0.0.0:1053                 
  ipv6: false                         

  enhanced-mode: redir-host

  nameserver:                         
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853

  fallback:                           
    - 'tls://1.1.1.1:853#DNS'         
    - 'tls://9.9.9.9:853#DNS'

  fallback-filter:                    
    geoip: true                       
    geoip-code: CN                    
    geosite:                         
      - gfw
    ipcidr:                          
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 233.252.0.0/24
      - 240.0.0.0/4
      - 255.255.255.255/32
      - 74.125.127.102/32
      - 74.125.155.102/32
      - 74.125.39.102/32
      - 74.125.39.113/32
      - 209.85.229.138/32
      - 128.121.126.139/32
      - 159.106.121.75/32
      - 169.132.13.103/32
      - 192.67.198.6/32
      - 202.106.1.2/32
      - 202.181.7.85/32
      - 203.161.230.171/32
      - 203.98.7.65/32
      - 207.12.88.98/32
      - 208.56.31.43/32
      - 209.145.54.50/32
      - 209.220.30.174/32
      - 209.36.73.33/32
      - 211.94.66.147/32
      - 213.169.251.35/32
      - 216.221.188.182/32
      - 216.234.179.13/32
      - 37.61.54.158/32
      - 4.36.66.178/32
      - 46.82.174.68/32
      - 59.24.3.173/32
      - 64.33.88.161/32
      - 64.33.99.47/32
      - 64.66.163.251/32
      - 65.104.202.252/32
      - 65.160.219.113/32
      - 66.45.252.237/32
      - 69.55.52.253/32
      - 72.14.205.104/32
      - 72.14.205.99/32
      - 78.16.49.15/32
      - 8.7.198.45/32
      - 93.46.8.89/32
      - 37.61.54.158/32
      - 190.93.247.4/32
      - 190.93.246.4/32
      - 190.93.245.4/32
      - 190.93.244.4/32
      - 65.49.2.178/32
      - 189.163.17.5/32
      - 23.89.5.60/32
      - 49.2.123.56/32
      - 54.76.135.1/32
      - 77.4.7.92/32
      - 118.5.49.6/32
      - 159.24.3.173/32
      - 188.5.4.96/32
      - 197.4.4.12/32
      - 220.250.64.24/32

proxies:
  - name: "KRCCEXP"
    type: hysteria
    server: krccexp.bgcine.xyz
    port: 2083
    obfs: mnHpc0f5
    alpn: h3
    protocol: udp
    up_mbps: 50
    down_mbps: 500

  - name: "KRCCNORM"
    type: trojan
    server: krccnorm.bgcine.xyz
    port: 443
    password: causeyousucksmotherfucker
    udp: true

  - name: "JPTYOEXP"
    type: hysteria
    server: jptyoexp.bgcine.xyz
    port: 2083
    obfs: 0vZcn3HR
    alpn: h3
    protocol: udp
    up_mbps: 50
    down_mbps: 500

  - name: "USSJEXP"
    type: hysteria
    server: ussjexp.bgcine.xyz
    port: 2083
    obfs: XnfCA1Mo
    alpn: h3
    protocol: udp
    up_mbps: 50
    down_mbps: 500

  - name: "vless-tcp"
    type: vless
    server: ussjexp.bgcine.xyz
    port: 443
    uuid: a5d27a4a-ed50-11ec-8ea0-0242ac120002
    network: tcp
    servername: example.com


proxy-groups:
  - name: Match
    type: select
    proxies:
      - Proxy

  - name: Microsoft
    type: select
    proxies:
      - DIRECT

  - name: Apple
    type: select
    proxies:
      - DIRECT

  - name: Google
    type: select
    proxies:
      - Proxy

  - name: Telegram
    type: select
    proxies:
      - Proxy

  - name: Netflix
    type: select
    proxies:
      - Proxy

  - name: Disney
    type: select
    proxies:
      - Proxy

  - name: Spotify
    type: select
    proxies:
      - Proxy

  - name: OracleKR
    type: select
    proxies:
      - KRCCEXP
      - KRCCNORM

  - name: OracleUS
    type: select
    proxies:
      - USSJEXP

  - name: AWSJP
    type: select
    proxies:
      - JPTYOEXP

  - name: Proxy
    type: select
    proxies:
      - OracleKR
      - OracleUS
      - AWSJP

rule-providers:

  Microsoft:
    type: http
    behavior: classical
    path: ./rule-providers/Microsoft.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    path: ./rule-providers/Apple.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    path: ./rule-providers/Google.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    path: ./rule-providers/YouTube.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    path: ./rule-providers/Telegram.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    path: ./rule-providers/Netflix.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml
    interval: 86400

  Disney:
    type: http
    behavior: classical
    path: ./rule-providers/Disney.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    path: ./rule-providers/Spotify.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml
    interval: 86400

rules:
  - GEOSITE,category-ads-all,REJECT
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Google,Google
  - RULE-SET,YouTube,Google
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney
  - RULE-SET,Spotify,Spotify
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,Proxy
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,Match